### ISSUE TITLE
Ugly title next to icon in the sidebar

### ISSUE THREAD

**Issue by creativefibro** [mihakralj/obsidian-textanalysis#3]
Where I have the tab open in my sidebar the plugin adds a large written title next to the icon. Non of the other plugins do this and it makes a mess of the layout. I can't find a way to turn this off anywhere. Please could you look into this. I love the functionality but this is distracting enough to make me want to close the panel. Thanks

![CleanShot 2024-01-21 at 5  37 23@2x](https://github.com/mihakralj/obsidian-textanalysis/assets/39191327/a9f98ee9-b95d-4517-8f69-e557faf20cd7)

![CleanShot 2024-01-21 at 5  28 09@2x](https://github.com/mihakralj/obsidian-textanalysis/assets/39191327/77b62cfc-8c1b-4993-b32f-eadca875b8a6)

**Comment by mihakralj** [comment]
You have a *really* weird CSS font modification that makes the title of the window pane so huge...  If you create a new empty/default vault and try plugin there, you'll see what the title typically looks like.

Adding the title to the window pane is an uncommon and less-than-trivial injection; that is why you don't see it often in many plugins. And it is actually unobtrusive when CSS sets a reasonable font setting.

But, you do you - and let me help you here. Are you proficient in editing .js files to follow instructions on how to change main.js file of the plugin so you can remove the title injection? As you are the only one complaining (due to an odd CSS you use), I'd prefer not to make a change for everyone as this pane title is the only place where you can see what the analysis is performed on (selection of text or the full document).

Alternatively, I can give you a modified main.js without the title that you can drop into your plugin folder.

Let me know.

**Comment by creativefibro** [comment]
I am using AnuPpuccin theme at the moment, is that the CSS you are talking about? Beyond style settings for the theme I haven't done anything else to change it that I know of, so I'm not sure why or how it is weird.

I tried it in a new default theme vault but found it was still larger than expected, something like the linked mentions size here:
![CleanShot 2024-01-21 at 6  50 17@2x](https://github.com/mihakralj/obsidian-textanalysis/assets/39191327/f8dc401c-2562-4875-b97e-50d06380c0ec)

I then tried moving it onto it's own level  in my main vault to see if I preferred the appearance and the heading moved to the new section and remain above even after a forced re-load so I have no idea what is going on there.

![CleanShot 2024-01-21 at 6  43 25@2x](https://github.com/mihakralj/obsidian-textanalysis/assets/39191327/eb54c219-309c-4e32-a569-aa89a8b646b4)

If you can give me the modified main.js that would be great. I just know that it will update to the highlighted section, if not it is the document.  Will it still remain if the plugin updates? Sorry beyond some basic HTLM and CSS I don't know code. Thanks

**Comment by mihakralj** [comment]
This is how it looks like with default CSS:
![CleanShot 2024-01-21 at 10 57 40@2x](https://github.com/mihakralj/obsidian-textanalysis/assets/31756078/2b9e6eb0-af90-4454-8a2d-504bac84dd85)

Let me think about how to solve this a bit more systemically.

**Comment by mihakralj** [comment]
OK, can you uninstall and re-install the plugin and let me know if the title disappeared and you are ok with this solution? I decided to simply remove the title of the plugin and call it quits. Let people deduct on their own what is analyzed - a full document or just a selection.
